# Generated by Django 4.0.6 on 2022-07-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=123123123123123123, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
