# Generated by Django 4.0.6 on 2022-07-22 17:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='published_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 7, 22, 17, 40, 37, 131639, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
