# Generated by Django 4.0.6 on 2022-07-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_blog_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[('skincare', 'Skin Care'), ('makeup', 'Makeup'), ('bath&body', 'Bath & Body')], default=('skincare', 'Skin Care'), max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
