# Generated by Django 4.0.6 on 2022-07-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_tag_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[('skincare', 'Skin Care'), ('makeup', 'Makeup'), ('bath&body', 'Bath & Body')], max_length=10),
        ),
    ]
