# Generated by Django 4.0.6 on 2022-07-24 09:54

import django.utils.timezone
import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_blog_image_alter_product_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='skin_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('normal', 'Normal'), ('combination', 'Combination'), ('oily', 'Oily')], default='oily', max_length=23),
            preserve_default=False,
        ),
    ]
