# Generated by Django 4.0.6 on 2022-07-24 10:05

import django.utils.timezone
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_blog_skin_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='formulation',
            field=models.CharField(choices=[('liquid', 'Liquid')], default='liquid', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='highlighted_ingredients',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ga', 'Glycolic Acid'), ('la', 'Lactic Acid'), ('sa', 'Salicylic Acid')], default='sa', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='skincare_concerns',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dullness', 'Dullness'), ('uneventexture', 'Uneven Texture'), ('acne', 'Acne'), ('blemishes', 'Blemishes')], default='acne', max_length=37),
            preserve_default=False,
        ),
    ]
